common: &common
  adapter: postgresql
  username: pourmeone_user
  password: pourmeone_pass
  min_messages: warning
  host: localhost
  port: 5432
  template: template0

development:
  <<: *common
  database: pourmeone_development

test:
  <<: *common
  database: pourmeone_test

production:
  <<: *common
  database: pourmeone_production
