common: &common
  adapter: postgresql
  username: pourmeone_user
  password: pourmeone_pass
  min_messages: warning
  port: 5433

development:
  <<: *common
  database: pourmeone_development 

test:
  database: pourmeone_test

production:
  database: pourmeone_production
