require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DrinksController do

  # This should return the minimal set of attributes required to create a valid
  # Drink. As you add validations to Drink, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { name: 'Old Fashioned', approved: true, ingredients: { raw_text: '2 oz Whiskey' } }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DrinksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do

    context "gets drinks based on approval status" do

      before(:all) do
        @approved = create(:drink)
        @not_approved = create(:drink, approved: false)
        @user = create(:user)
        @admin = create(:user, admin: true)
      end

      it "assigns all approved drinks as @drinks if no user is signed in" do
        get :index
        assigns(:drinks).should eq([@approved])
      end

      it "assigns all approved drinks as @drinks if the signed-in user is not an admin" do
        sign_in @user
        get :index
        assigns(:drinks).should eq([@approved])
      end

      it "assigns all drinks as @drinks if the signed-in user is an admin" do
        sign_in @admin
        get :index
        assigns(:drinks).should eq([@approved, @not_approved])
      end

      after(:all) do
        @approved.destroy
        @not_approved.destroy
        @user.destroy
        @admin.destroy
        Ingredient.delete_all
      end
    end

    it "renders the :index view" do
      get :index
      expect(response).to render_template :index
    end
  end

  describe "GET show" do
    it "assigns the requested drink as @drink" do
      drink = create(:drink)
      get :show, {:id => drink.to_param}, valid_session
      assigns(:drink).should eq(drink)
    end

    it "renders the :show template" do
      drink = create(:drink)
      get :show, id: drink
      expect(response).to render_template :show
    end
  end

  describe "GET new" do
    it "assigns a new drink as @drink" do
      get :new, {}, valid_session
      assigns(:drink).should be_a_new(Drink)
    end

    it "renders the :new template" do
      get :new
      expect(response).to render_template :new
    end
  end

  describe "GET edit" do
    it "assigns the requested drink as @drink" do
      drink = create(:drink)
      get :edit, {:id => drink.to_param}, valid_session
      assigns(:drink).should eq(drink)
    end

    it "renders the :edit template" do
      drink = create(:drink)
      get :edit, id: drink
      expect(response).to render_template :edit
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Drink" do
        expect {
          post :create, {:drink => valid_attributes}, valid_session
        }.to change(Drink, :count).by(1)
      end

      it "assigns a newly created drink as @drink" do
        post :create, {:drink => valid_attributes}, valid_session
        assigns(:drink).should be_a(Drink)
        assigns(:drink).should be_persisted
      end

      it "redirects to the created drink" do
        post :create, {:drink => valid_attributes}, valid_session
        response.should redirect_to(Drink.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved drink as @drink" do
        # Trigger the behavior that occurs when invalid params are submitted
        Drink.any_instance.stub(:save).and_return(false)
        post :create, {:drink => {}}, valid_session
        assigns(:drink).should be_a_new(Drink)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Drink.any_instance.stub(:save).and_return(false)
        post :create, {:drink => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested drink" do
        drink = create(:drink)
        # Assuming there are no other drinks in the database, this
        # specifies that the Drink created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Drink.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => drink.to_param, :drink => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested drink as @drink" do
        drink = create(:drink)
        put :update, {:id => drink.to_param, :drink => valid_attributes.except(:ingredients)}, valid_session
        assigns(:drink).should eq(drink)
      end

      it "redirects to the drink" do
        drink = create(:drink)
        put :update, {:id => drink.to_param, :drink => valid_attributes.except(:ingredients)}, valid_session
        response.should redirect_to(drink)
      end
    end

    describe "with invalid params" do
      it "assigns the drink as @drink" do
        drink = create(:drink)
        # Trigger the behavior that occurs when invalid params are submitted
        Drink.any_instance.stub(:save).and_return(false)
        put :update, {:id => drink.to_param, :drink => {}}, valid_session
        assigns(:drink).should eq(drink)
      end

      it "re-renders the 'edit' template" do
        drink = create(:drink)
        # Trigger the behavior that occurs when invalid params are submitted
        Drink.any_instance.stub(:save).and_return(false)
        put :update, {:id => drink.to_param, :drink => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested drink" do
      drink = create(:drink)
      expect {
        delete :destroy, {:id => drink.to_param}, valid_session
      }.to change(Drink, :count).by(-1)
    end

    it "redirects to the drinks list" do
      drink = create(:drink)
      delete :destroy, {:id => drink.to_param}, valid_session
      response.should redirect_to(drinks_url)
    end
  end

end
